/*
 * MenuBarPanel.java
 *
 * Created on 21. November 2005, 20:12
 */

package de.hampelratte.test;

/**
 *
 * @author  TBN
 */
public class MenuBarPanel extends javax.swing.JPanel {
	
	/** Creates new form MenuBarPanel */
	public MenuBarPanel() {
		initComponents();
	}
	
	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jInternalFrame4 = new javax.swing.JInternalFrame();
        jMenuBar4 = new javax.swing.JMenuBar();
        jMenu19 = new javax.swing.JMenu();
        jMenuItem25 = new javax.swing.JMenuItem();
        jMenuItem26 = new javax.swing.JMenuItem();
        jSeparator34 = new javax.swing.JSeparator();
        jCheckBoxMenuItem25 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem26 = new javax.swing.JCheckBoxMenuItem();
        jSeparator35 = new javax.swing.JSeparator();
        jRadioButtonMenuItem25 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem26 = new javax.swing.JRadioButtonMenuItem();
        jSeparator36 = new javax.swing.JSeparator();
        jMenu20 = new javax.swing.JMenu();
        jMenuItem27 = new javax.swing.JMenuItem();
        jMenuItem28 = new javax.swing.JMenuItem();
        jSeparator37 = new javax.swing.JSeparator();
        jCheckBoxMenuItem27 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem28 = new javax.swing.JCheckBoxMenuItem();
        jSeparator38 = new javax.swing.JSeparator();
        jRadioButtonMenuItem27 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem28 = new javax.swing.JRadioButtonMenuItem();
        jMenu21 = new javax.swing.JMenu();
        jMenuItem29 = new javax.swing.JMenuItem();
        jMenuItem30 = new javax.swing.JMenuItem();
        jSeparator39 = new javax.swing.JSeparator();
        jCheckBoxMenuItem29 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem30 = new javax.swing.JCheckBoxMenuItem();
        jSeparator40 = new javax.swing.JSeparator();
        jRadioButtonMenuItem29 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem30 = new javax.swing.JRadioButtonMenuItem();
        jSeparator41 = new javax.swing.JSeparator();
        jMenu22 = new javax.swing.JMenu();
        jMenu23 = new javax.swing.JMenu();
        jMenuItem31 = new javax.swing.JMenuItem();
        jMenuItem32 = new javax.swing.JMenuItem();
        jSeparator42 = new javax.swing.JSeparator();
        jCheckBoxMenuItem31 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem32 = new javax.swing.JCheckBoxMenuItem();
        jSeparator43 = new javax.swing.JSeparator();
        jRadioButtonMenuItem31 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem32 = new javax.swing.JRadioButtonMenuItem();
        jSeparator44 = new javax.swing.JSeparator();
        jMenu24 = new javax.swing.JMenu();

        setLayout(new java.awt.BorderLayout());

        setName("JMenuBar");
        jInternalFrame4.setVisible(true);
        jMenu19.setText("Menu");
        jMenuItem25.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/CrystalSVG/folder.png")));
        jMenuItem25.setMnemonic('I');
        jMenuItem25.setText("Item");
        jMenu19.add(jMenuItem25);

        jMenuItem26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/CrystalSVG/folder_new.png")));
        jMenuItem26.setText("Item");
        jMenu19.add(jMenuItem26);

        jMenu19.add(jSeparator34);

        jCheckBoxMenuItem25.setText("CheckBox");
        jMenu19.add(jCheckBoxMenuItem25);

        jCheckBoxMenuItem26.setText("CheckBox");
        jMenu19.add(jCheckBoxMenuItem26);

        jMenu19.add(jSeparator35);

        jRadioButtonMenuItem25.setText("RadioButton");
        jMenu19.add(jRadioButtonMenuItem25);

        jRadioButtonMenuItem26.setText("RadioButton");
        jMenu19.add(jRadioButtonMenuItem26);

        jMenu19.add(jSeparator36);

        jMenu20.setText("Menu");
        jMenuItem27.setText("Item");
        jMenu20.add(jMenuItem27);

        jMenuItem28.setText("Item");
        jMenu20.add(jMenuItem28);

        jMenu20.add(jSeparator37);

        jCheckBoxMenuItem27.setText("CheckBox");
        jMenu20.add(jCheckBoxMenuItem27);

        jCheckBoxMenuItem28.setText("CheckBox");
        jMenu20.add(jCheckBoxMenuItem28);

        jMenu20.add(jSeparator38);

        jRadioButtonMenuItem27.setText("RadioButton");
        jMenu20.add(jRadioButtonMenuItem27);

        jRadioButtonMenuItem28.setText("RadioButton");
        jMenu20.add(jRadioButtonMenuItem28);

        jMenu19.add(jMenu20);

        jMenuBar4.add(jMenu19);

        jMenu21.setText("Disabled");
        jMenuItem29.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/CrystalSVG/folder.png")));
        jMenuItem29.setMnemonic('I');
        jMenuItem29.setText("Item");
        jMenuItem29.setEnabled(false);
        jMenu21.add(jMenuItem29);

        jMenuItem30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/CrystalSVG/folder_new.png")));
        jMenuItem30.setText("Item");
        jMenuItem30.setEnabled(false);
        jMenu21.add(jMenuItem30);

        jSeparator39.setEnabled(false);
        jMenu21.add(jSeparator39);

        jCheckBoxMenuItem29.setText("CheckBox");
        jCheckBoxMenuItem29.setEnabled(false);
        jMenu21.add(jCheckBoxMenuItem29);

        jCheckBoxMenuItem30.setText("CheckBox");
        jCheckBoxMenuItem30.setEnabled(false);
        jMenu21.add(jCheckBoxMenuItem30);

        jSeparator40.setEnabled(false);
        jMenu21.add(jSeparator40);

        jRadioButtonMenuItem29.setText("RadioButton");
        jRadioButtonMenuItem29.setEnabled(false);
        jMenu21.add(jRadioButtonMenuItem29);

        jRadioButtonMenuItem30.setText("RadioButton");
        jRadioButtonMenuItem30.setEnabled(false);
        jMenu21.add(jRadioButtonMenuItem30);

        jSeparator41.setEnabled(false);
        jMenu21.add(jSeparator41);

        jMenu22.setText("Menu");
        jMenu22.setEnabled(false);
        jMenu21.add(jMenu22);

        jMenuBar4.add(jMenu21);

        jMenu23.setText("Menu");
        jMenuItem31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/CrystalSVG/folder.png")));
        jMenuItem31.setText("Item");
        jMenu23.add(jMenuItem31);

        jMenuItem32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/CrystalSVG/folder_new.png")));
        jMenuItem32.setText("Item");
        jMenu23.add(jMenuItem32);

        jMenu23.add(jSeparator42);

        jCheckBoxMenuItem31.setText("CheckBox");
        jMenu23.add(jCheckBoxMenuItem31);

        jCheckBoxMenuItem32.setText("CheckBox");
        jMenu23.add(jCheckBoxMenuItem32);

        jMenu23.add(jSeparator43);

        jRadioButtonMenuItem31.setText("RadioButton");
        jMenu23.add(jRadioButtonMenuItem31);

        jRadioButtonMenuItem32.setText("RadioButton");
        jMenu23.add(jRadioButtonMenuItem32);

        jMenu23.add(jSeparator44);

        jMenu24.setText("Menu");
        jMenu23.add(jMenu24);

        jMenuBar4.add(jMenu23);

        jInternalFrame4.setJMenuBar(jMenuBar4);

        add(jInternalFrame4, java.awt.BorderLayout.CENTER);

    }
    // </editor-fold>//GEN-END:initComponents
	
	
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem25;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem26;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem27;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem28;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem29;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem30;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem31;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem32;
    private javax.swing.JInternalFrame jInternalFrame4;
    private javax.swing.JMenu jMenu19;
    private javax.swing.JMenu jMenu20;
    private javax.swing.JMenu jMenu21;
    private javax.swing.JMenu jMenu22;
    private javax.swing.JMenu jMenu23;
    private javax.swing.JMenu jMenu24;
    private javax.swing.JMenuBar jMenuBar4;
    private javax.swing.JMenuItem jMenuItem25;
    private javax.swing.JMenuItem jMenuItem26;
    private javax.swing.JMenuItem jMenuItem27;
    private javax.swing.JMenuItem jMenuItem28;
    private javax.swing.JMenuItem jMenuItem29;
    private javax.swing.JMenuItem jMenuItem30;
    private javax.swing.JMenuItem jMenuItem31;
    private javax.swing.JMenuItem jMenuItem32;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem25;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem26;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem27;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem28;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem29;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem30;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem31;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem32;
    private javax.swing.JSeparator jSeparator34;
    private javax.swing.JSeparator jSeparator35;
    private javax.swing.JSeparator jSeparator36;
    private javax.swing.JSeparator jSeparator37;
    private javax.swing.JSeparator jSeparator38;
    private javax.swing.JSeparator jSeparator39;
    private javax.swing.JSeparator jSeparator40;
    private javax.swing.JSeparator jSeparator41;
    private javax.swing.JSeparator jSeparator42;
    private javax.swing.JSeparator jSeparator43;
    private javax.swing.JSeparator jSeparator44;
    // End of variables declaration//GEN-END:variables
	
}
