/*
 * ToggleButtonPanel.java
 *
 * Created on 21. November 2005, 20:07
 */

package de.hampelratte.test;

/**
 *
 * @author  TBN
 */
public class ToggleButtonPanel extends javax.swing.JPanel {
	
	/** Creates new form ToggleButtonPanel */
	public ToggleButtonPanel() {
		initComponents();
	}
	
	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jToggleButton3 = new javax.swing.JToggleButton();
        jToggleButton4 = new javax.swing.JToggleButton();
        jToggleButton5 = new javax.swing.JToggleButton();
        jToggleButton6 = new javax.swing.JToggleButton();
        jToggleButton7 = new javax.swing.JToggleButton();
        jToggleButton8 = new javax.swing.JToggleButton();
        jToggleButton9 = new javax.swing.JToggleButton();
        jToggleButton10 = new javax.swing.JToggleButton();
        jToggleButton11 = new javax.swing.JToggleButton();
        jToggleButton12 = new javax.swing.JToggleButton();
        jToggleButton13 = new javax.swing.JToggleButton();
        jToggleButton14 = new javax.swing.JToggleButton();
        jToggleButton15 = new javax.swing.JToggleButton();
        jToggleButton16 = new javax.swing.JToggleButton();

        setLayout(new java.awt.GridBagLayout());

        setName("JToggleButton");
        jToggleButton1.setText("jToggleButton1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(jToggleButton1, gridBagConstraints);

        jToggleButton2.setSelected(true);
        jToggleButton2.setText("jToggleButton2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(jToggleButton2, gridBagConstraints);

        jToggleButton3.setText("jToggleButton3");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(jToggleButton3, gridBagConstraints);

        jToggleButton4.setSelected(true);
        jToggleButton4.setText("jToggleButton4");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(jToggleButton4, gridBagConstraints);

        jToggleButton5.setText("jToggleButton5");
        jToggleButton5.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(jToggleButton5, gridBagConstraints);

        jToggleButton6.setSelected(true);
        jToggleButton6.setText("jToggleButton6");
        jToggleButton6.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(jToggleButton6, gridBagConstraints);

        jToggleButton7.setText("jToggleButton7");
        jToggleButton7.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(jToggleButton7, gridBagConstraints);

        jToggleButton8.setSelected(true);
        jToggleButton8.setText("jToggleButton8");
        jToggleButton8.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(jToggleButton8, gridBagConstraints);

        jToggleButton9.setBackground(new java.awt.Color(255, 204, 51));
        jToggleButton9.setForeground(new java.awt.Color(255, 0, 0));
        jToggleButton9.setText("jToggleButton9");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(jToggleButton9, gridBagConstraints);

        jToggleButton10.setBackground(new java.awt.Color(255, 204, 51));
        jToggleButton10.setForeground(new java.awt.Color(255, 0, 0));
        jToggleButton10.setSelected(true);
        jToggleButton10.setText("jToggleButton10");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(jToggleButton10, gridBagConstraints);

        jToggleButton11.setBackground(new java.awt.Color(255, 204, 51));
        jToggleButton11.setForeground(new java.awt.Color(255, 0, 0));
        jToggleButton11.setText("jToggleButton11");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(jToggleButton11, gridBagConstraints);

        jToggleButton12.setBackground(new java.awt.Color(255, 204, 51));
        jToggleButton12.setForeground(new java.awt.Color(255, 0, 0));
        jToggleButton12.setSelected(true);
        jToggleButton12.setText("jToggleButton12");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(jToggleButton12, gridBagConstraints);

        jToggleButton13.setBackground(new java.awt.Color(255, 204, 51));
        jToggleButton13.setForeground(new java.awt.Color(255, 0, 0));
        jToggleButton13.setText("jToggleButton13");
        jToggleButton13.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(jToggleButton13, gridBagConstraints);

        jToggleButton14.setBackground(new java.awt.Color(255, 204, 51));
        jToggleButton14.setForeground(new java.awt.Color(255, 0, 0));
        jToggleButton14.setSelected(true);
        jToggleButton14.setText("jToggleButton14");
        jToggleButton14.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(jToggleButton14, gridBagConstraints);

        jToggleButton15.setBackground(new java.awt.Color(255, 204, 51));
        jToggleButton15.setForeground(new java.awt.Color(255, 0, 0));
        jToggleButton15.setText("jToggleButton15");
        jToggleButton15.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(jToggleButton15, gridBagConstraints);

        jToggleButton16.setBackground(new java.awt.Color(255, 204, 51));
        jToggleButton16.setForeground(new java.awt.Color(255, 0, 0));
        jToggleButton16.setSelected(true);
        jToggleButton16.setText("jToggleButton16");
        jToggleButton16.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(jToggleButton16, gridBagConstraints);

    }
    // </editor-fold>//GEN-END:initComponents
	
	
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton10;
    private javax.swing.JToggleButton jToggleButton11;
    private javax.swing.JToggleButton jToggleButton12;
    private javax.swing.JToggleButton jToggleButton13;
    private javax.swing.JToggleButton jToggleButton14;
    private javax.swing.JToggleButton jToggleButton15;
    private javax.swing.JToggleButton jToggleButton16;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JToggleButton jToggleButton4;
    private javax.swing.JToggleButton jToggleButton5;
    private javax.swing.JToggleButton jToggleButton6;
    private javax.swing.JToggleButton jToggleButton7;
    private javax.swing.JToggleButton jToggleButton8;
    private javax.swing.JToggleButton jToggleButton9;
    // End of variables declaration//GEN-END:variables
	
}
